ident				::= "-"? <nmstart> <nmchar>*
name				::= <nmchar>+
nmstart				::= [_a-z] | <nonascii> | <escape>
nonascii			::= ^[#0-#177]
unicode				::= "\\" [0-9a-f] [0-9a-f]? [0-9a-f]? [0-9a-f]? [0-9a-f]? [0-9a-f]? ("\r\n"| [ \n\r\t\f] )?
escape				::= <unicode> | "\\" [^\n\r\f0-9a-f]
nmchar				::= [_a-z0-9-] | <nonascii> | <escape>
num					::= [0-9]+ | [0-9]* "." [0-9]+
string				::= <string1> | <string2>
string1   			::= "\"" (^[\n\r\f\\"] | "\\" <nl> | <nonascii> | <escape>)* "\""
string2   			::= "\'" (^[\n\r\f\\'] | "\\" <nl> | <nonascii> | <escape>)* "\'"
invalid				::= <invalid1> | <invalid2>
invalid1			::= "\"" ([^\n\r\f\\"] | \\<nl>| <nonascii> | <escape>)*
invalid2			::= "\'" ([^\n\r\f\\"] | \\<nl>| <nonascii> | <escape>)*
nl					::= "\n" | "\r\n" | "\r" | "\0"
w					::= [ \t\r\n\f]*

function			::= <ident> "("
hash				::= "#" <name>
plus				::= <space>* "+"
greater				::= <space>* ">"
tilde				::= <space>* "~"
not					::= ":" "not" "("
rule				::= <space>* <selectorsGroup> <space>+ "{" (<property>? ";")* (<property>? ";"*)? "}"
propertyName		::= (<alpha> | <digit> | "-")+
propertyValue		::= (<alpha> | <digit> | "-" | "." | <space> | "#" | "," | "%")+ <space>* "!important"?
property			::= <propertyName> <space>* ":" <space>* <propertyValue>
