
# http://www.w3.org/TR/CSS2/syndata.html#vendor-keywords

prefixMicrosoft		::= "-ms-" | "mso-"
prefixMozilla		::= "-moz-"
prefixOpera			::= "-o-" | "-xv-"
prefixKhtml			::= "-khtml-"
prefixWebkit		::= "-webkit-"
vendorPrefix		::= <prefixMicrosoft> | <prefixMozilla> | <prefixOpera> | <prefixKhtml> | <prefixWebkit>
